//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://zpd", ConfigurationName="IZPDService")]
public interface IZPDService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://zpd/IZPDService/Play", ReplyAction="http://zpd/IZPDService/PlayResponse")]
    void Play();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://zpd/IZPDService/Pause", ReplyAction="http://zpd/IZPDService/PauseResponse")]
    void Pause();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://zpd/IZPDService/Close", ReplyAction="http://zpd/IZPDService/CloseResponse")]
    void Close();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IZPDServiceChannel : IZPDService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ZPDServiceClient : System.ServiceModel.ClientBase<IZPDService>, IZPDService
{
    
    public ZPDServiceClient()
    {
    }
    
    public ZPDServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ZPDServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ZPDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ZPDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Play()
    {
        base.Channel.Play();
    }
    
    public void Pause()
    {
        base.Channel.Pause();
    }
    
    public void Close()
    {
        base.Channel.Close();
    }
}
